In [161]:
pip install underthesea

In [3]:
import nltk
import underthesea
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [4]:
import re
import pandas as pd
import unicodedata

In [5]:
filename = 'sentimentVN.csv'
df = pd.read_csv(filename)
print(df.shape)

(31460, 3)


In [6]:

filename_list=[]
with open(filename) as file:
  for line in file:
      a = line.lower()
      a = unicodedata.normalize('NFC', a) # chuyển đổi unico tổ hợp -> dựng sẵn
      
      a = a.rstrip('\n')
      a = re.sub(r"[^a-zA-Z0-9đàáảãạâầấẩẫậăằắẳẵặèéẻẽẹêềếểễệđìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵ]"," ",a)
      a = re.sub(r'\s+', ' ', a).strip()# xóa khoản trắng dư thừa
      filename_list.append(a )

In [57]:
data = df.values
print(data.shape)
lines = data[:,1]
label = data[:,2]

(31460, 3)


In [58]:
print(lines[:5])
print(label[:5])

['áo bao đẹp ạ positive' 'tuyệt vời positive' '2day ao không giong trong'
 'mùi thơm bôi lên da mềm da nagative positive' 'vải đẹp dày dặn positive']
['POS' 'POS' 'NEG' 'POS' 'POS']


In [59]:
from underthesea import word_tokenize
import nltk 
import numpy as np

In [60]:
sentences = []
labels=[]
for i in range(len(lines)):
  try:
    sentences.append(word_tokenize(lines[i]))
    labels.append(word_tokenize(label[i]))
  except:
    print(i)

1462
1931
3730
8194
8355
10181
17982
20142
22059
23510
24343
25543
25703
27954
28009
28402
28741
29145
29231
29509
30010
30154
30907
30992
31447


In [187]:
# tách từ trong từng câu 
print(sentences[:5])
print(labels[:15])
print(sentences[:15])
print(len(sentences))
print(len(labels))


[['áo bao', 'đẹp', 'ạ', 'positive'], ['tuyệt vời', 'positive'], ['2', 'day', 'ao', 'không', 'giong', 'trong'], ['mùi', 'thơm', 'bôi', 'lên da', 'mềm', 'da', 'nagative', 'positive'], ['vải', 'đẹp', 'dày dặn', 'positive']]
[['POS'], ['POS'], ['NEG'], ['POS'], ['POS'], ['POS'], ['POS'], ['POS'], ['POS'], ['NEG'], ['POS'], ['NEU'], ['POS'], ['POS'], ['POS']]
[['áo bao', 'đẹp', 'ạ', 'positive'], ['tuyệt vời', 'positive'], ['2', 'day', 'ao', 'không', 'giong', 'trong'], ['mùi', 'thơm', 'bôi', 'lên da', 'mềm', 'da', 'nagative', 'positive'], ['vải', 'đẹp', 'dày dặn', 'positive'], ['hàng', 'rất', 'đẹp', 'rất', 'chi là', 'ưng ý', 'positive', 'positive'], ['chất lượng', 'sản phẩm', 'tốt', 'hạn', 'sử dụng', 'dài', 'positive', 'positive'], ['ăn nói', 'và', 'thái độ', 'phục vụ', 'tốt', 'positive'], ['đóng', 'gói', 'sản phẩm', 'chắc chắn', 'positive'], ['tất', 'sờn', 'hết', 'ca', 'chưa', 'dùng', 'mà', 'vay', 'r'], ['cửa', 'hàng', 'phục vụ', 'rất', 'tốt', 'positive'], ['mặc', 'thì', 'cũng', 'được', 'po

In [62]:
from tensorflow.keras.preprocessing.text import Tokenizer 
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
# kiểm tra từ điểm tạo trong tokenizer
#print(tokenizer.word_index)

In [120]:
#texts_to_matrix(tokenizer, texts, mode = c("binary", "count", "tfidf", "freq"))
X = tokenizer.texts_to_matrix(sentences,mode='binary')
print(X.shape)
print(X[0])

(31435, 6885)
[0. 1. 0. ... 0. 0. 0.]


In [141]:
# chia tập train và tập test 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, labels, 
                                            test_size=0.2, random_state=0)

In [131]:
print(len(y_test))
print(len(X_test))

6287
6287


In [162]:
print(y_train)

[['POS'], ['NEG'], ['POS'], ['NEG'], ['NEU'], ['NEG'], ['NEG'], ['POS'], ['POS'], ['POS'], ['POS'], ['POS'], ['POS'], ['POS'], ['POS'], ['POS'], ['POS'], ['NEU'], ['POS'], ['POS'], ['NEG'], ['POS'], ['NEG'], ['POS'], ['NEU'], ['POS'], ['POS'], ['NEG'], ['POS'], ['POS'], ['POS'], ['POS'], ['NEG'], ['NEG'], ['POS'], ['NEU'], ['NEG'], ['POS'], ['POS'], ['POS'], ['POS'], ['POS'], ['POS'], ['NEU'], ['POS'], ['POS'], ['POS'], ['POS'], ['POS'], ['POS'], ['POS'], ['NEG'], ['POS'], ['NEG'], ['NEG'], ['NEG'], ['NEG'], ['NEG'], ['POS'], ['POS'], ['POS'], ['POS'], ['NEU'], ['POS'], ['NEU'], ['POS'], ['POS'], ['POS'], ['NEG'], ['NEG'], ['NEG'], ['NEU'], ['POS'], ['NEG'], ['POS'], ['NEG'], ['POS'], ['POS'], ['NEG'], ['POS'], ['NEG'], ['POS'], ['POS'], ['NEU'], ['POS'], ['POS'], ['POS'], ['POS'], ['NEU'], ['POS'], ['NEG'], ['NEG'], ['POS'], ['POS'], ['NEU'], ['POS'], ['POS'], ['POS'], ['POS'], ['NEU'], ['POS'], ['POS'], ['NEU'], ['NEU'], ['POS'], ['POS'], ['POS'], ['POS'], ['POS'], ['NEG'], ['NEG'], 

In [142]:
from sklearn.preprocessing import LabelEncoder
lbencoder = LabelEncoder()
y_train2 = lbencoder.fit_transform(y_train)
print(y_train2.shape)
print(y_train2[:14])

(25148,)
[2 0 2 0 1 0 0 2 2 2 2 2 2 2]


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [143]:
from tensorflow.keras.utils import to_categorical
y_train2 = to_categorical(y_train2, num_classes=3 )
print(y_train2.shape)
print(y_train2[:3,:])

(25148, 3)
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [150]:
print(X.shape[1])

6885


In [163]:
# sử dụng Neural Networks 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(20, input_dim=X.shape[1], activation='sigmoid'))
model.add(Dense(20, activation='sigmoid'))
model.add(Dense(20, activation='sigmoid'))
model.add(Dense(3, activation='softmax'))

In [164]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_28 (Dense)            (None, 20)                137720    
                                                                 
 dense_29 (Dense)            (None, 20)                420       
                                                                 
 dense_30 (Dense)            (None, 20)                420       
                                                                 
 dense_31 (Dense)            (None, 3)                 63        
                                                                 
Total params: 138,623
Trainable params: 138,623
Non-trainable params: 0
_________________________________________________________________


In [165]:
#train 
model.fit(X_train, y_train2, epochs=20, batch_size=100)

Epoch 1/20
252/252 [==============================] - 3s 9ms/step - loss: 0.5762 - accuracy: 0.5868
Epoch 2/20
252/252 [==============================] - 2s 9ms/step - loss: 0.4660 - accuracy: 0.6634
Epoch 3/20
252/252 [==============================] - 2s 9ms/step - loss: 0.3529 - accuracy: 0.7735
Epoch 4/20
252/252 [==============================] - 2s 9ms/step - loss: 0.3284 - accuracy: 0.7874
Epoch 5/20
252/252 [==============================] - 2s 9ms/step - loss: 0.3169 - accuracy: 0.7936
Epoch 6/20
252/252 [==============================] - 2s 9ms/step - loss: 0.3076 - accuracy: 0.7982
Epoch 7/20
252/252 [==============================] - 2s 9ms/step - loss: 0.2998 - accuracy: 0.8026
Epoch 8/20
252/252 [==============================] - 2s 9ms/step - loss: 0.2927 - accuracy: 0.8058
Epoch 9/20
252/252 [==============================] - 2s 9ms/step - loss: 0.2859 - accuracy: 0.8119
Epoch 10/20
252/252 [==============================] - 2s 9ms/step - loss: 0.2795 - accuracy: 0.8185

In [166]:
y_test1 = lbencoder.fit_transform(y_test)
y_test2 = to_categorical(y_test1, 3)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [167]:
y_pred = model.predict(X_test)

In [168]:
print(y_pred[:10])

[[1.6873781e-05 1.7355842e-04 9.9980956e-01]
 [2.3700615e-05 2.4091059e-04 9.9973541e-01]
 [9.3693137e-01 5.3932950e-02 9.1356179e-03]
 [8.8202059e-06 7.6357319e-05 9.9991477e-01]
 [1.1445772e-05 9.9766177e-05 9.9988878e-01]
 [9.3733150e-01 5.2047621e-02 1.0620831e-02]
 [3.1529915e-05 3.3777324e-04 9.9963069e-01]
 [3.5964913e-05 3.6570165e-04 9.9959832e-01]
 [8.8457118e-06 7.6619392e-05 9.9991453e-01]
 [9.5461720e-01 3.7517440e-02 7.8653870e-03]]


In [173]:
y_pred1 = np.argmax(y_pred,axis=1)
print(y_pred1[:100])

[2 2 0 2 2 0 2 2 2 0 2 2 0 2 2 2 2 2 0 2 2 2 0 0 0 2 0 1 2 1 2 0 0 0 2 2 1
 2 1 1 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 0 0 0 0 2 0 2 2 2 2 2 1 2 2
 2 2 1 1 2 0 2 0 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 1 2 1]


In [174]:
from sklearn.metrics import classification_report
print(classification_report(y_test1,y_pred1))

              precision    recall  f1-score   support

           0       0.71      0.73      0.72      1366
           1       0.39      0.30      0.34       936
           2       0.87      0.91      0.89      3985

    accuracy                           0.78      6287
   macro avg       0.66      0.65      0.65      6287
weighted avg       0.77      0.78      0.77      6287



In [232]:
input_sent = 'mặc thì tạm được, hợp túi tiền'
# dự đoán?
tokens = nltk.word_tokenize(input_sent)
print(tokens)
X_input = tokenizer.texts_to_matrix([tokens],mode='binary')
print(X_input)

['mặc', 'thì', 'tạm', 'được', ',', 'hợp', 'túi', 'tiền']
[[0. 0. 0. ... 0. 0. 0.]]


In [233]:
y_pred = model.predict(X_input)
y_pred1 = np.argmax(y_pred,axis=1)
print(y_pred1[0])

1


In [234]:
def check(pred):
  if str(pred[0]) == "2":
    return "Tích cực"
  elif str(pred[0]) == '1':
    return "Trung lập"
  else:
    return "Tiêu cực"

print(check(y_pred1))

Trung lập
